using System.Runtime.InteropServices;
namespace CSharp.WinAPI.Tasks;
/// <summary>Reads local Task Scheduler metadata without registering, changing, or executing tasks.</summary>
public sealed class ScheduledTaskInspector
{
    private const int MaximumFolders = 2_048, MaximumDepth = 16, MaximumTasks = 16_384, MaximumPathLength = 32_768, MaximumStringLength = 16_384, MaximumTriggers = 128, MaximumActions = 128;
    /// <summary>Enumerates an immutable, bounded snapshot of local scheduled-task metadata.</summary>
    public IReadOnlyList<ScheduledTaskInfo> EnumerateTasks(string? folderPath = null)
    {
        var rootPath = ValidateFolder(folderPath ?? "\\"); using var apartment = TaskSchedulerComApartment.Enter(); object? service = null; try { service = CreateService(); ((dynamic)service).Connect(); object? root = null; try { root = ((dynamic)service).GetFolder(rootPath); var result = new List<ScheduledTaskInfo>(); var folders = 0; Visit(root, rootPath, 0, ref folders, result); return Array.AsReadOnly(result.ToArray()); } finally { Release(root); } } catch (ScheduledTaskInspectionException) { throw; } catch (Exception ex) { throw new ScheduledTaskInspectionException("Task Scheduler enumeration", rootPath, ex); } finally { Release(service); }
    }
    private static object CreateService() => Activator.CreateInstance(Type.GetTypeFromCLSID(new Guid("0F87369F-A4E5-4CFC-BD3E-73E6154572DD"))!) ?? throw new InvalidOperationException("Task Scheduler COM activation returned null.");
    private static void Visit(object folder, string path, int depth, ref int folders, List<ScheduledTaskInfo> result)
    {
        if (depth > MaximumDepth || ++folders > MaximumFolders) throw new ScheduledTaskInspectionException("Task folder enumeration", path, "The configured folder bound was exceeded."); dynamic f = folder; object? tasks = null; try { tasks = f.GetTasks(1); var count = checked((int)((dynamic)tasks).Count); if (count < 0 || count > MaximumTasks || result.Count > MaximumTasks - count) throw new ScheduledTaskInspectionException("Task enumeration", path, "The configured task bound was exceeded."); for (var i = 1; i <= count; i++) { object? task = null; try { task = ((dynamic)tasks)[i]; result.Add(Read(task, path)); } finally { Release(task); } } } finally { Release(tasks); }
        object? children = null; try { children = f.GetFolders(0); var count = checked((int)((dynamic)children).Count); if (count < 0 || count > MaximumFolders - folders) throw new ScheduledTaskInspectionException("Task folder enumeration", path, "The configured folder bound was exceeded."); for (var i = 1; i <= count; i++) { object? child = null; try { child = ((dynamic)children)[i]; Visit(child, Text(((dynamic)child).Path, "folder path", path) ?? throw new ScheduledTaskInspectionException("Task folder enumeration", path, "A child folder had no path."), depth + 1, ref folders, result); } finally { Release(child); } } } finally { Release(children); }
    }
    private static ScheduledTaskInfo Read(object task, string folder)
    {
        dynamic t = task; var path = Text(t.Path, "task path", folder) ?? throw new ScheduledTaskInspectionException("Read task", folder, "A task had no path."); object? definition = null; try { definition = t.Definition; dynamic d = definition; object? registration = null; object? principal = null; object? settings = null; try { registration = d.RegistrationInfo; principal = d.Principal; settings = d.Settings; dynamic r = registration; dynamic p = principal; dynamic s = settings; return new ScheduledTaskInfo(path, Text(t.Name, "task name", path) ?? string.Empty, folder, State(Convert.ToInt32(t.State)), Convert.ToBoolean(t.Enabled), new ScheduledTaskRegistrationInfo(Text(r.Author,"author",path),Text(r.Description,"description",path),Text(r.Source,"source",path),Text(r.Version,"version",path),Text(r.Date,"date",path)), new ScheduledTaskPrincipalInfo(Text(p.UserId,"user",path),Text(p.GroupId,"group",path),Convert.ToInt32(p.LogonType),Convert.ToInt32(p.RunLevel)), new ScheduledTaskSettingsInfo(Convert.ToBoolean(s.Enabled),Convert.ToBoolean(s.Hidden),Convert.ToBoolean(s.AllowDemandStart),Convert.ToBoolean(s.StartWhenAvailable),Convert.ToInt32(s.Priority),Text(s.ExecutionTimeLimit,"execution limit",path)), Triggers(d.Triggers,path), Actions(d.Actions,path)); } finally { Release(settings); Release(principal); Release(registration); } } finally { Release(definition); }
    }
    private static IReadOnlyList<ScheduledTaskTriggerInfo> Triggers(dynamic collection, string path) { object c = collection; try { var count=checked((int)collection.Count); if(count<0||count>MaximumTriggers) throw new ScheduledTaskInspectionException("Read triggers",path,"The configured trigger bound was exceeded."); var list=new List<ScheduledTaskTriggerInfo>(count); for(var i=1;i<=count;i++){object? x=null; object? repeat=null; try{x=collection[i]; dynamic q=x; repeat=q.Repetition; dynamic r=repeat; list.Add(new(Convert.ToInt32(q.Type),Convert.ToBoolean(q.Enabled),Text(q.StartBoundary,"start boundary",path),Text(q.EndBoundary,"end boundary",path),Text(r.Interval,"repetition interval",path),Text(r.Duration,"repetition duration",path)));}finally{Release(repeat);Release(x);}} return list.Count==0?Array.Empty<ScheduledTaskTriggerInfo>():Array.AsReadOnly(list.ToArray());} finally { Release(c); } }
    private static IReadOnlyList<ScheduledTaskActionInfo> Actions(dynamic collection, string path) { object c=collection; try { var count=checked((int)collection.Count); if(count<0||count>MaximumActions) throw new ScheduledTaskInspectionException("Read actions",path,"The configured action bound was exceeded."); var list=new List<ScheduledTaskActionInfo>(count); for(var i=1;i<=count;i++){object? x=null;try{x=collection[i];dynamic a=x;var type=Convert.ToInt32(a.Type);list.Add(type==0?new(type,Text(a.Path,"action path",path),Text(a.Arguments,"arguments",path),Text(a.WorkingDirectory,"working directory",path),null):type==5?new(type,null,null,null,Text(a.ClassId,"class id",path)):new(type,null,null,null,null));}finally{Release(x);}}return list.Count==0?Array.Empty<ScheduledTaskActionInfo>():Array.AsReadOnly(list.ToArray());}finally{Release(c);} }
    private static ScheduledTaskStateInfo State(int raw) => new(raw, raw switch { 0 => ScheduledTaskState.Unknown, 1 => ScheduledTaskState.Disabled, 2 => ScheduledTaskState.Queued, 3 => ScheduledTaskState.Ready, 4 => ScheduledTaskState.Running, _ => ScheduledTaskState.Unknown });
    private static string ValidateFolder(string value) { ArgumentException.ThrowIfNullOrWhiteSpace(value); if(value.Length>MaximumPathLength||value.IndexOf('\0')>=0||value[0]!='\\') throw new ArgumentException("The folder path must be rooted, bounded, and contain no null characters.",nameof(value)); return value; }
    private static string? Text(object? value,string field,string path) { var text=value?.ToString(); if(text is {Length:>MaximumStringLength}||text?.IndexOf('\0')>=0) throw new ScheduledTaskInspectionException($"Read {field}",path,"A string exceeded the configured bound or contained a null character."); return text; }
    private static void Release(object? value) { if(value is not null&&Marshal.IsComObject(value)) _=Marshal.FinalReleaseComObject(value); }
}
