using System.Management;
namespace CSharp.WinAPI.Wmi;
/// <summary>Provides bounded, local-only WMI class metadata and instance inspection without method invocation or mutation.</summary>
public sealed class WmiInspector
{
    private const int MaximumNamespaceLength=256, MaximumClassNameLength=256, MaximumClasses=4096, MaximumProperties=256, MaximumInstances=1024, MaximumString=64*1024;
    /// <summary>Enumerates local class metadata in a validated namespace.</summary>
    public IReadOnlyList<WmiClassInfo> EnumerateClasses(WmiNamespacePath path)
    {
        var nameSpace=ValidateNamespace(path); using var apartment=WmiComApartment.Enter(); try { using var searcher=new ManagementObjectSearcher(Scope(nameSpace),new ObjectQuery("SELECT * FROM meta_class")); using var objects=searcher.Get(); var list=new List<WmiClassInfo>(); foreach(ManagementObject item in objects){using(item){if(list.Count==MaximumClasses)throw new WmiInspectionException("Enumerate WMI classes",nameSpace,null,"The class limit was exceeded.");var name=Text(item["__CLASS"],nameSpace,null,"class name")??throw new WmiInspectionException("Enumerate WMI classes",nameSpace,null,"A class had no name.");list.Add(ReadClass(nameSpace,name));}}return Array.AsReadOnly(list.ToArray());}catch(WmiInspectionException){throw;}catch(Exception ex){throw new WmiInspectionException("Enumerate WMI classes",nameSpace,null,ex);}
    }
    /// <summary>Reads bounded metadata for one local WMI class.</summary>
    public WmiClassInfo InspectClass(WmiNamespacePath path,string className) { var ns=ValidateNamespace(path); ValidateClass(className); using var apartment=WmiComApartment.Enter(); try{return ReadClass(ns,className);}catch(WmiInspectionException){throw;}catch(Exception ex){throw new WmiInspectionException("Inspect WMI class",ns,className,ex);} }
    /// <summary>Reads up to <paramref name="maximumInstances"/> local instances of one validated WMI class.</summary>
    public IReadOnlyList<WmiInstanceInfo> QueryInstances(WmiNamespacePath path,string className,int maximumInstances=32)
    { var ns=ValidateNamespace(path);ValidateClass(className);if(maximumInstances is <1 or >MaximumInstances)throw new ArgumentOutOfRangeException(nameof(maximumInstances));using var apartment=WmiComApartment.Enter();try{using var searcher=new ManagementObjectSearcher(Scope(ns),new ObjectQuery($"SELECT * FROM {className}"));using var objects=searcher.Get();var list=new List<WmiInstanceInfo>();foreach(ManagementObject item in objects){using(item){if(list.Count==maximumInstances)break;var props=new List<WmiPropertyValue>();foreach(PropertyData p in item.Properties){if(props.Count==MaximumProperties)throw new WmiInspectionException("Read WMI instance",ns,className,"The property limit was exceeded.");props.Add(new(p.Name,p.Type.ToString(),p.Value is null,Value(p.Value,ns,className)));}list.Add(new(className,props.Count==0?Array.Empty<WmiPropertyValue>():Array.AsReadOnly(props.ToArray())));}}return list.Count==0?Array.Empty<WmiInstanceInfo>():Array.AsReadOnly(list.ToArray());}catch(WmiInspectionException){throw;}catch(Exception ex){throw new WmiInspectionException("Query WMI instances",ns,className,ex);} }
    private static WmiClassInfo ReadClass(string ns,string className){using var c=new ManagementClass(Scope(ns),new ManagementPath(className),null);var props=new List<WmiPropertyInfo>();foreach(PropertyData p in c.Properties){if(props.Count==MaximumProperties)throw new WmiInspectionException("Read WMI class",ns,className,"The property limit was exceeded.");props.Add(new(p.Name,p.Type.ToString(),p.IsArray));}return new(className,Text(c["__SUPERCLASS"],ns,className,"parent class"),props.Count==0?Array.Empty<WmiPropertyInfo>():Array.AsReadOnly(props.ToArray()));}
    private static ManagementScope Scope(string ns)=>new($"\\\\.\\{ns}");
    private static string ValidateNamespace(WmiNamespacePath path){ArgumentNullException.ThrowIfNull(path);var value=path.Namespace;ArgumentException.ThrowIfNullOrWhiteSpace(value);if(value.Length>MaximumNamespaceLength||value.IndexOf('\0')>=0||value.Contains("\\\\",StringComparison.Ordinal)||value.StartsWith("\\",StringComparison.Ordinal)||!value.StartsWith("ROOT\\",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("The namespace must be a bounded local ROOT namespace.",nameof(path));return value;}
    private static void ValidateClass(string value){ArgumentException.ThrowIfNullOrWhiteSpace(value);if(value.Length>MaximumClassNameLength||value.IndexOf('\0')>=0||!value.All(c=>char.IsLetterOrDigit(c)||c=='_'))throw new ArgumentException("The class name was invalid.",nameof(value));}
    private static string? Text(object? value,string ns,string? c,string field)=>value is null?null:Bound(value.ToString(),ns,c,field);
    private static string? Value(object? value,string ns,string c){if(value is null)return null;if(value is Array a){if(a.Length>MaximumProperties)throw new WmiInspectionException("Read WMI property",ns,c,"The array element limit was exceeded.");return Bound(string.Join(",",a.Cast<object?>().Select(x=>x?.ToString()??"<null>")),ns,c,"property value");}return Bound(value switch{string s=>s,bool b=>b?"true":"false",IFormattable f=>f.ToString(null,System.Globalization.CultureInfo.InvariantCulture),_=>value.GetType().FullName??"<unsupported>"},ns,c,"property value");}
    private static string? Bound(string? value,string ns,string? c,string field){if(value is {Length:>MaximumString})throw new WmiInspectionException($"Read WMI {field}",ns,c,"The string limit was exceeded.");return value;}
}
